spring:
  application:
    name: ServiceSavedFilm
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Den/25362004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
server:
  port: 8085
servicedb:
  api:
    url: http://localhost:8081